### ISSUE TITLE
Python3 version & Django 2.0

### ISSUE THREAD

**Issue by CodeMath** [genonfire/bbgo#2]
Python3 version & Django 2.0 버전 호환이 안되는 것으로 보니,
2.7버전에 1.8이네요...(Django 2.0 이상 버전에 대한 계획이 있으신지 궁금합니다.)

(제가 조금 씩 손을 보긴하는데 지금;;)

**Comment by genonfire** [comment]
http://jira.gencode.me/browse/BBGO-92

**Comment by genonfire** [comment]
이제 Django 1.11 LTS 와 Django 2.0.2(Python 3.6.0) 동시에 지원합니다.

https://github.com/genonfire/bbgo/commit/8fd85936f664774510fea912c3f6ab9f66c0f608
